name: Comments Transferor

on:
  issue_comment:
    types: [created]
  workflow_call:
    secrets:
      gh_token:
        required: true

jobs:
  build:
    if: ${{ github.event.issue.number == 1 }}
    runs-on: ubuntu-latest
    concurrency:
      group: comments-transferor
      cancel-in-progress: true
    steps:
      - name: Transfer comments
        uses: noraworld/comments-transferor@main
        with:
          issue_repo: 'noraworld/social-media-recorder' # for workflow_call
          issue_number: '1'                             # for workflow_call
          target_issue_repo: noraworld/reserved-diary
          target_issue_number: latest
          personal_access_token: GH_TOKEN
          replace_twitter_short_url: true
          trim_empty_image_tag: true
          linkify_hashtags: true
          linkify_mentions: true
          move_trailing_urls_to_next_lines: true
          remove_spaces_after_japanese_punctuation: true
          trim_misskey_profile_icon_url: true
          replace_misskey_image_url_with_multiple_ones: true
        env:
          GITHUB_TOKEN:  ${{ secrets.gh_token || secrets.GH_TOKEN }}
