name: Social Media Double

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: ${{ github.event.issue.number == 2 }}
    runs-on: ubuntu-latest
    concurrency:
      group: social-media-double
      cancel-in-progress: true
    steps:
      - name: Post to social media
        uses: noraworld/social-media-double@main
        with:
          misskey_api_token: MISSKEY_API_KEY
          misskey_server: misskey.io
          personal_access_token: GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MISSKEY_API_KEY: ${{ secrets.MISSKEY_API_KEY }}
